### ISSUE TITLE
Remove references to "Sling"

### ISSUE THREAD

**Issue by rombert** [stone-payments/emerald-web-framework#364]
We appreciate the actions taken to date to rename the project to reduce the likelihood of confusion of this project with [Apache Sling](https://sling.apache.org/). However, we note that a number of references to Sling remain.

The Apache Sling [PMC](https://www.apache.org/dev/pmc.html) has reviewed the changes from the ['emd-master'](https://github.com/stone-payments/emerald-web-framework/tree/emd-master) branch as of commit 5c5a634a1cd4d87e222efc41323a1ddfb36cf319 and has concluded that they would resolve the remaining concerns.

Please merge the changes from the 'emd-master' branch into 'master' as soon as possible.

Regards,
Robert Munteanu,VP Apache Sling, Apache Software Foundation

**Comment by breakzplatform** [comment]
@rombert Thanks for your message. We're working on it.

We still need support the old version of Emerald (the "Sling" version) for compatibility. So, here's what we gonna do with your branches:

- Move `master` to `emd-legacy`;
- Move `develop` to `emd-legacy-develop`
- Change `emd-master` to `master`
- Change `emd-develop` to `develop`

Does it work for you?

Thank you for the patience

**Comment by rombert** [comment]
Thank you for your reply @breakzplatform. The changes you proposed look good to us. When would you expect them to be complete?

Regards,
Robert Munteanu,VP Apache Sling, Apache Software Foundation

**Comment by rombert** [comment]
We have noticed that after commit e10a67bf15be20b128d632b336286426a227f65b all occurences of 'Sling' have been removed, which is what this issue is asking.

Thank you for your work on this.

Regards,
Robert Munteanu,VP Apache Sling, Apache Software Foundation
